// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: cosmos/accounts/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "../../../google/protobuf/any";

export const protobufPackage = "cosmos.accounts.v1";

/** AccountQueryRequest is the request type for the Query/AccountQuery RPC */
export interface AccountQueryRequest {
  /** target defines the account to be queried. */
  target: string;
  /** request defines the query message being sent to the account. */
  request?: Any | undefined;
}

/** AccountQueryResponse is the response type for the Query/AccountQuery RPC method. */
export interface AccountQueryResponse {
  /** response defines the query response of the account. */
  response?: Any | undefined;
}

/** SchemaResponse is the response type for the Query/Schema RPC method. */
export interface SchemaRequest {
  /** account_type defines the account type to query the schema for. */
  accountType: string;
}

/** SchemaResponse is the response type for the Query/Schema RPC method. */
export interface SchemaResponse {
  /** init_schema defines the schema descriptor for the Init account method. */
  initSchema?:
    | SchemaResponse_Handler
    | undefined;
  /** execute_handlers defines the schema descriptor for the Execute account method. */
  executeHandlers: SchemaResponse_Handler[];
  /** query_handlers defines the schema descriptor for the Query account method. */
  queryHandlers: SchemaResponse_Handler[];
}

/**
 * Handler defines a schema descriptor for a handler.
 * Where request and response are names that can be used to lookup the
 * reflection descriptor.
 */
export interface SchemaResponse_Handler {
  /** request is the request name */
  request: string;
  /** response is the response name */
  response: string;
}

/** AccountTypeRequest is the request type for the Query/AccountType RPC method. */
export interface AccountTypeRequest {
  /** address defines the address to query the account type for. */
  address: string;
}

/** AccountTypeResponse is the response type for the Query/AccountType RPC method. */
export interface AccountTypeResponse {
  /** account_type defines the account type for the address. */
  accountType: string;
}

/** AccountNumberRequest returns the account number given the address. */
export interface AccountNumberRequest {
  /** address is the address of the account we want to know the number of. */
  address: string;
}

/**
 * AccountNumberResponse is the response returned when querying the
 * account number by address.
 */
export interface AccountNumberResponse {
  /** number is the account number of the provided address. */
  number: string;
}

function createBaseAccountQueryRequest(): AccountQueryRequest {
  return { target: "", request: undefined };
}

export const AccountQueryRequest: MessageFns<AccountQueryRequest> = {
  encode(message: AccountQueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.target !== "") {
      writer.uint32(10).string(message.target);
    }
    if (message.request !== undefined) {
      Any.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountQueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountQueryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountQueryRequest {
    return {
      target: isSet(object.target) ? globalThis.String(object.target) : "",
      request: isSet(object.request) ? Any.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: AccountQueryRequest): unknown {
    const obj: any = {};
    if (message.target !== "") {
      obj.target = message.target;
    }
    if (message.request !== undefined) {
      obj.request = Any.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<AccountQueryRequest>): AccountQueryRequest {
    return AccountQueryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountQueryRequest>): AccountQueryRequest {
    const message = createBaseAccountQueryRequest();
    message.target = object.target ?? "";
    message.request = (object.request !== undefined && object.request !== null)
      ? Any.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseAccountQueryResponse(): AccountQueryResponse {
  return { response: undefined };
}

export const AccountQueryResponse: MessageFns<AccountQueryResponse> = {
  encode(message: AccountQueryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== undefined) {
      Any.encode(message.response, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountQueryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountQueryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountQueryResponse {
    return { response: isSet(object.response) ? Any.fromJSON(object.response) : undefined };
  },

  toJSON(message: AccountQueryResponse): unknown {
    const obj: any = {};
    if (message.response !== undefined) {
      obj.response = Any.toJSON(message.response);
    }
    return obj;
  },

  create(base?: DeepPartial<AccountQueryResponse>): AccountQueryResponse {
    return AccountQueryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountQueryResponse>): AccountQueryResponse {
    const message = createBaseAccountQueryResponse();
    message.response = (object.response !== undefined && object.response !== null)
      ? Any.fromPartial(object.response)
      : undefined;
    return message;
  },
};

function createBaseSchemaRequest(): SchemaRequest {
  return { accountType: "" };
}

export const SchemaRequest: MessageFns<SchemaRequest> = {
  encode(message: SchemaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountType !== "") {
      writer.uint32(10).string(message.accountType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SchemaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSchemaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accountType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SchemaRequest {
    return { accountType: isSet(object.accountType) ? globalThis.String(object.accountType) : "" };
  },

  toJSON(message: SchemaRequest): unknown {
    const obj: any = {};
    if (message.accountType !== "") {
      obj.accountType = message.accountType;
    }
    return obj;
  },

  create(base?: DeepPartial<SchemaRequest>): SchemaRequest {
    return SchemaRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SchemaRequest>): SchemaRequest {
    const message = createBaseSchemaRequest();
    message.accountType = object.accountType ?? "";
    return message;
  },
};

function createBaseSchemaResponse(): SchemaResponse {
  return { initSchema: undefined, executeHandlers: [], queryHandlers: [] };
}

export const SchemaResponse: MessageFns<SchemaResponse> = {
  encode(message: SchemaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.initSchema !== undefined) {
      SchemaResponse_Handler.encode(message.initSchema, writer.uint32(10).fork()).join();
    }
    for (const v of message.executeHandlers) {
      SchemaResponse_Handler.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.queryHandlers) {
      SchemaResponse_Handler.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SchemaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSchemaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.initSchema = SchemaResponse_Handler.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.executeHandlers.push(SchemaResponse_Handler.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.queryHandlers.push(SchemaResponse_Handler.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SchemaResponse {
    return {
      initSchema: isSet(object.initSchema) ? SchemaResponse_Handler.fromJSON(object.initSchema) : undefined,
      executeHandlers: globalThis.Array.isArray(object?.executeHandlers)
        ? object.executeHandlers.map((e: any) => SchemaResponse_Handler.fromJSON(e))
        : [],
      queryHandlers: globalThis.Array.isArray(object?.queryHandlers)
        ? object.queryHandlers.map((e: any) => SchemaResponse_Handler.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SchemaResponse): unknown {
    const obj: any = {};
    if (message.initSchema !== undefined) {
      obj.initSchema = SchemaResponse_Handler.toJSON(message.initSchema);
    }
    if (message.executeHandlers?.length) {
      obj.executeHandlers = message.executeHandlers.map((e) => SchemaResponse_Handler.toJSON(e));
    }
    if (message.queryHandlers?.length) {
      obj.queryHandlers = message.queryHandlers.map((e) => SchemaResponse_Handler.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SchemaResponse>): SchemaResponse {
    return SchemaResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SchemaResponse>): SchemaResponse {
    const message = createBaseSchemaResponse();
    message.initSchema = (object.initSchema !== undefined && object.initSchema !== null)
      ? SchemaResponse_Handler.fromPartial(object.initSchema)
      : undefined;
    message.executeHandlers = object.executeHandlers?.map((e) => SchemaResponse_Handler.fromPartial(e)) || [];
    message.queryHandlers = object.queryHandlers?.map((e) => SchemaResponse_Handler.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSchemaResponse_Handler(): SchemaResponse_Handler {
  return { request: "", response: "" };
}

export const SchemaResponse_Handler: MessageFns<SchemaResponse_Handler> = {
  encode(message: SchemaResponse_Handler, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request !== "") {
      writer.uint32(10).string(message.request);
    }
    if (message.response !== "") {
      writer.uint32(18).string(message.response);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SchemaResponse_Handler {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSchemaResponse_Handler();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.request = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.response = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SchemaResponse_Handler {
    return {
      request: isSet(object.request) ? globalThis.String(object.request) : "",
      response: isSet(object.response) ? globalThis.String(object.response) : "",
    };
  },

  toJSON(message: SchemaResponse_Handler): unknown {
    const obj: any = {};
    if (message.request !== "") {
      obj.request = message.request;
    }
    if (message.response !== "") {
      obj.response = message.response;
    }
    return obj;
  },

  create(base?: DeepPartial<SchemaResponse_Handler>): SchemaResponse_Handler {
    return SchemaResponse_Handler.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SchemaResponse_Handler>): SchemaResponse_Handler {
    const message = createBaseSchemaResponse_Handler();
    message.request = object.request ?? "";
    message.response = object.response ?? "";
    return message;
  },
};

function createBaseAccountTypeRequest(): AccountTypeRequest {
  return { address: "" };
}

export const AccountTypeRequest: MessageFns<AccountTypeRequest> = {
  encode(message: AccountTypeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountTypeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountTypeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountTypeRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: AccountTypeRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountTypeRequest>): AccountTypeRequest {
    return AccountTypeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountTypeRequest>): AccountTypeRequest {
    const message = createBaseAccountTypeRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseAccountTypeResponse(): AccountTypeResponse {
  return { accountType: "" };
}

export const AccountTypeResponse: MessageFns<AccountTypeResponse> = {
  encode(message: AccountTypeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountType !== "") {
      writer.uint32(10).string(message.accountType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountTypeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountTypeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accountType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountTypeResponse {
    return { accountType: isSet(object.accountType) ? globalThis.String(object.accountType) : "" };
  },

  toJSON(message: AccountTypeResponse): unknown {
    const obj: any = {};
    if (message.accountType !== "") {
      obj.accountType = message.accountType;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountTypeResponse>): AccountTypeResponse {
    return AccountTypeResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountTypeResponse>): AccountTypeResponse {
    const message = createBaseAccountTypeResponse();
    message.accountType = object.accountType ?? "";
    return message;
  },
};

function createBaseAccountNumberRequest(): AccountNumberRequest {
  return { address: "" };
}

export const AccountNumberRequest: MessageFns<AccountNumberRequest> = {
  encode(message: AccountNumberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountNumberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountNumberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountNumberRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: AccountNumberRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountNumberRequest>): AccountNumberRequest {
    return AccountNumberRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountNumberRequest>): AccountNumberRequest {
    const message = createBaseAccountNumberRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseAccountNumberResponse(): AccountNumberResponse {
  return { number: "0" };
}

export const AccountNumberResponse: MessageFns<AccountNumberResponse> = {
  encode(message: AccountNumberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.number !== "0") {
      writer.uint32(8).uint64(message.number);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountNumberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountNumberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.number = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountNumberResponse {
    return { number: isSet(object.number) ? globalThis.String(object.number) : "0" };
  },

  toJSON(message: AccountNumberResponse): unknown {
    const obj: any = {};
    if (message.number !== "0") {
      obj.number = message.number;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountNumberResponse>): AccountNumberResponse {
    return AccountNumberResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountNumberResponse>): AccountNumberResponse {
    const message = createBaseAccountNumberResponse();
    message.number = object.number ?? "0";
    return message;
  },
};

/** Query defines the Query service for the x/accounts module. */
export interface Query {
  /** AccountQuery runs an account query. */
  AccountQuery(request: AccountQueryRequest): Promise<AccountQueryResponse>;
  /** Schema returns an x/account schema. Unstable. */
  Schema(request: SchemaRequest): Promise<SchemaResponse>;
  /** AccountType returns the account type for an address. */
  AccountType(request: AccountTypeRequest): Promise<AccountTypeResponse>;
  /** AccountNumber returns the account number given the account address. */
  AccountNumber(request: AccountNumberRequest): Promise<AccountNumberResponse>;
}

export const QueryServiceName = "cosmos.accounts.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.AccountQuery = this.AccountQuery.bind(this);
    this.Schema = this.Schema.bind(this);
    this.AccountType = this.AccountType.bind(this);
    this.AccountNumber = this.AccountNumber.bind(this);
  }
  AccountQuery(request: AccountQueryRequest): Promise<AccountQueryResponse> {
    const data = AccountQueryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AccountQuery", data);
    return promise.then((data) => AccountQueryResponse.decode(new BinaryReader(data)));
  }

  Schema(request: SchemaRequest): Promise<SchemaResponse> {
    const data = SchemaRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Schema", data);
    return promise.then((data) => SchemaResponse.decode(new BinaryReader(data)));
  }

  AccountType(request: AccountTypeRequest): Promise<AccountTypeResponse> {
    const data = AccountTypeRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AccountType", data);
    return promise.then((data) => AccountTypeResponse.decode(new BinaryReader(data)));
  }

  AccountNumber(request: AccountNumberRequest): Promise<AccountNumberResponse> {
    const data = AccountNumberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AccountNumber", data);
    return promise.then((data) => AccountNumberResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
