// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: cosmos/gov/module/v1/module.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cosmos.gov.module.v1";

/** Module is the config object of the gov module. */
export interface Module {
  /**
   * max_metadata_len defines the maximum proposal metadata length.
   * Defaults to 255 if not explicitly set.
   */
  maxMetadataLen: string;
  /** authority defines the custom module authority. If not set, defaults to the governance module. */
  authority: string;
  /**
   * max_title_len defines the maximum proposal title length.
   * Defaults to 255 if not explicitly set.
   */
  maxTitleLen: string;
  /**
   * max_summary_len defines the maximum proposal summary length.
   * Defaults to 10200 if not explicitly set.
   */
  maxSummaryLen: string;
}

function createBaseModule(): Module {
  return { maxMetadataLen: "0", authority: "", maxTitleLen: "0", maxSummaryLen: "0" };
}

export const Module: MessageFns<Module> = {
  encode(message: Module, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxMetadataLen !== "0") {
      writer.uint32(8).uint64(message.maxMetadataLen);
    }
    if (message.authority !== "") {
      writer.uint32(18).string(message.authority);
    }
    if (message.maxTitleLen !== "0") {
      writer.uint32(24).uint64(message.maxTitleLen);
    }
    if (message.maxSummaryLen !== "0") {
      writer.uint32(32).uint64(message.maxSummaryLen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Module {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxMetadataLen = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxTitleLen = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxSummaryLen = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Module {
    return {
      maxMetadataLen: isSet(object.maxMetadataLen) ? globalThis.String(object.maxMetadataLen) : "0",
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      maxTitleLen: isSet(object.maxTitleLen) ? globalThis.String(object.maxTitleLen) : "0",
      maxSummaryLen: isSet(object.maxSummaryLen) ? globalThis.String(object.maxSummaryLen) : "0",
    };
  },

  toJSON(message: Module): unknown {
    const obj: any = {};
    if (message.maxMetadataLen !== "0") {
      obj.maxMetadataLen = message.maxMetadataLen;
    }
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.maxTitleLen !== "0") {
      obj.maxTitleLen = message.maxTitleLen;
    }
    if (message.maxSummaryLen !== "0") {
      obj.maxSummaryLen = message.maxSummaryLen;
    }
    return obj;
  },

  create(base?: DeepPartial<Module>): Module {
    return Module.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Module>): Module {
    const message = createBaseModule();
    message.maxMetadataLen = object.maxMetadataLen ?? "0";
    message.authority = object.authority ?? "";
    message.maxTitleLen = object.maxTitleLen ?? "0";
    message.maxSummaryLen = object.maxSummaryLen ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
