// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: cosmos/accounts/testing/rotation/v1/partial.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cosmos.accounts.testing.rotation.v1";

/**
 * MsgInit is the init message used to create a new account
 * abstraction implementation that we use for testing, this account
 * also allows for rotating the public key.
 */
export interface MsgInit {
  pubKeyBytes: Uint8Array;
}

/** MsgInitResponse is the init message response. */
export interface MsgInitResponse {
}

/**
 * MsgRotatePubKey is the message used to swap the public key
 * of the account.
 */
export interface MsgRotatePubKey {
  newPubKeyBytes: Uint8Array;
}

/** MsgRotatePubKeyResponse is the MsgRotatePubKey response. */
export interface MsgRotatePubKeyResponse {
}

function createBaseMsgInit(): MsgInit {
  return { pubKeyBytes: new Uint8Array(0) };
}

export const MsgInit: MessageFns<MsgInit> = {
  encode(message: MsgInit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pubKeyBytes.length !== 0) {
      writer.uint32(10).bytes(message.pubKeyBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgInit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgInit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pubKeyBytes = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgInit {
    return { pubKeyBytes: isSet(object.pubKeyBytes) ? bytesFromBase64(object.pubKeyBytes) : new Uint8Array(0) };
  },

  toJSON(message: MsgInit): unknown {
    const obj: any = {};
    if (message.pubKeyBytes.length !== 0) {
      obj.pubKeyBytes = base64FromBytes(message.pubKeyBytes);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgInit>): MsgInit {
    return MsgInit.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgInit>): MsgInit {
    const message = createBaseMsgInit();
    message.pubKeyBytes = object.pubKeyBytes ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgInitResponse(): MsgInitResponse {
  return {};
}

export const MsgInitResponse: MessageFns<MsgInitResponse> = {
  encode(_: MsgInitResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgInitResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgInitResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgInitResponse {
    return {};
  },

  toJSON(_: MsgInitResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgInitResponse>): MsgInitResponse {
    return MsgInitResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgInitResponse>): MsgInitResponse {
    const message = createBaseMsgInitResponse();
    return message;
  },
};

function createBaseMsgRotatePubKey(): MsgRotatePubKey {
  return { newPubKeyBytes: new Uint8Array(0) };
}

export const MsgRotatePubKey: MessageFns<MsgRotatePubKey> = {
  encode(message: MsgRotatePubKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newPubKeyBytes.length !== 0) {
      writer.uint32(10).bytes(message.newPubKeyBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRotatePubKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRotatePubKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.newPubKeyBytes = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRotatePubKey {
    return {
      newPubKeyBytes: isSet(object.newPubKeyBytes) ? bytesFromBase64(object.newPubKeyBytes) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgRotatePubKey): unknown {
    const obj: any = {};
    if (message.newPubKeyBytes.length !== 0) {
      obj.newPubKeyBytes = base64FromBytes(message.newPubKeyBytes);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgRotatePubKey>): MsgRotatePubKey {
    return MsgRotatePubKey.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgRotatePubKey>): MsgRotatePubKey {
    const message = createBaseMsgRotatePubKey();
    message.newPubKeyBytes = object.newPubKeyBytes ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgRotatePubKeyResponse(): MsgRotatePubKeyResponse {
  return {};
}

export const MsgRotatePubKeyResponse: MessageFns<MsgRotatePubKeyResponse> = {
  encode(_: MsgRotatePubKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRotatePubKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRotatePubKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRotatePubKeyResponse {
    return {};
  },

  toJSON(_: MsgRotatePubKeyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgRotatePubKeyResponse>): MsgRotatePubKeyResponse {
    return MsgRotatePubKeyResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgRotatePubKeyResponse>): MsgRotatePubKeyResponse {
    const message = createBaseMsgRotatePubKeyResponse();
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
