name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # ESLint and Prettier must be in `package.json`
      # --frozen-lockfile ensures lockfile will not be updated
      - name: Install yarn via corepack
        run: corepack enable && corepack prepare yarn@1.22.22 --activate

      - name: Install dependencies with yarn
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn check-format
